const CANVAS_DIMENSIONS = {
  WIDTH: 640,
  HEIGHT: window.innerHeight,
};

const PLAYER_DIMENSIONS = {
  WIDTH: 92,
  HEIGHT: 92,
};

const PLATFORM_DIMENSIONS = {};

export { CANVAS_DIMENSIONS, PLAYER_DIMENSIONS, PLATFORM_DIMENSIONS };
